### ISSUE TITLE
Changing output directory doesn't actually change the output directory

### ISSUE THREAD

**Issue by SenseiLeRoof** [Petschko/Java-RPG-Maker-MV-Decrypter#11]
As title.
Worse, the selected directory is emptied.

**Comment by Petschko** [comment]
Really? That should not be! Let me have a look at this when I'm home...

If work would not stress me so much out, I had made more improvements and fixes anyway...

Thanks for reporting, else I didn't noticed this issue

You just changed the Directory and it got emptied? Or did you something else please explain the steps you've done, so that I can redo and debug it at home

**Comment by Petschko** [comment]
https://github.com/Petschko/Java-RPG-Maker-MV-Decrypter/commit/61af7fadc43212e7af07c1d7a300f3063460b054
Set clearing the Output dir to disabled by default (Hotfix) but I will investigate the issue about the not changing of the dir

**Comment by Petschko** [comment]
That should fix the issue https://github.com/Petschko/Java-RPG-Maker-MV-Decrypter/commit/09361e259d668aacc3d194d73af1809bbd4fd225

Will add this fix to the next release
