### ISSUE TITLE
Display Loaded Files in GUI

### ISSUE THREAD

**Issue by kanink007** [Petschko/Java-RPG-Maker-MV-Decrypter#15]
hello. i have some .rpgmvo files and the system.js
i dont have the full game, only these files. and i want to batch decrypt the files i have.
problem is: when i select the folder with files, it says "this is no rpg mv directory. but you can load invalid DIRs then anyways." 
i check the box for invalid dirs, but the files are still not loaded and it still says, there is no decryption key when i click "decrypt All"
what am i doing wrong? the files are in a folder with the system.js
i cant set decryption code manually, either. its greyed out. (i guess that because the java script doesnt load the files in the first place). so, what do i need to do?

**Comment by RedAISkye** [comment]
Same, the "Set Decryption Key" option is disabled for some reason.

**Comment by Petschko** [comment]
Yes, the Problem, is that this Programm is in the "ALPHA" Stage, which means I have to develop BASIC-Functions.
However, the Programm itself is able to do some work already, but as you noticed, there are some functions not implemented yet. (Like the Add-Encryption-Key by yourself)

See here: https://github.com/Petschko/Java-RPG-Maker-MV-Decrypter/issues/9

If you really want to decrypt lose-files, you can do one of these Options:

- Use my Web-Decrypter, which is out of the Alpha Stage and is designed for lose files: http://petschko.org/tools/mv_decrypter/ | https://github.com/Petschko/RPG-Maker-MV-Decrypter
- Try to build a Directory-Structure like a normal RPG-Maker-Game and put the files in their Folder, where they belong - If it complains then about an invalid RPG-Dir, you can then use the function "ignore invalid dirs". But the structure need to be like any RPG-Maker Project, else it wont detect the key and Files

----

I'm super sorry, I didn't (or just really less) work on my Github Projects for since 1 Year... The reason is, I'm exhausted from work, so I didn't have much motivation to code at home as well, because there is no Progres at work... I hope I refind my motivation soon, I really want finish/fix some issues here...

**Comment by Petschko** [comment]
@RedEyedRocker See/Comment here for the "Add Key Issue" https://github.com/Petschko/Java-RPG-Maker-MV-Decrypter/issues/9

But I need to rework the GUI which should help and display the loaded files! To avoid confusion like this!

**Comment by Petschko** [comment]
Added: https://github.com/Petschko/Java-RPG-Maker-MV-Decrypter/releases/tag/v.0.4.0-alpha
