### ISSUE TITLE
Can't Decyrpt Anything on Java 10.0.1

### ISSUE THREAD

**Issue by ghost** [Petschko/Java-RPG-Maker-MV-Decrypter#16]
Using RPG-Maker MV Decrypter - v0.1.3.1 (Hotfix) Alpha
This program doesn't work with Java 10, after selecting a project, project is loaded message doesn't appear and all the decrypt options is not available.

I also tried the command line and the error it gives:
Exception in thread "main" java.lang.NoClassDefFoundError: sun/dc/path/PathException
        at org.petschko.rpgmakermv.decrypt.App.main(App.java:41)
Caused by: java.lang.ClassNotFoundException: sun.dc.path.PathException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more

I then switched back to Java 9 including Java 8 and it worked.

**Comment by Petschko** [comment]
Hello,
thanks for reporting this issue! I need more informations:
-> Can you please tell me your **OS** and architecture _(Example: Windows 7 Home 64bit)_
-> Java-Version (Sun Java 10 x64 or Open JDK etc)

Thanks so far^^

**Comment by RedAISkye** [comment]
Same for me, when I installed Java 10, it didn't work for me so I had to go back to Java 8.
My OS is Windows 10 x64 bit

**Comment by Petschko** [comment]
Hello,

I've read a bit about the new Java-Versions and was first a bit unsure how I could miss them. But to be honest, Java 10 is just a **Short-Time-Release** (Support ends in Sept 2018) while Java 8 has support until Jan 2019~Dez 2020 (or even later)

![Java-Version-Support roadmap](https://jaxenter.com/wp-content/uploads/2018/03/Screen-Shot-2018-03-27-at-11.40.47-AM.png)
also readable here:
http://www.oracle.com/technetwork/java/eol-135779.html

The next **LTS** (LongTimeSupport) Release is **Java 11**. I will not rewrite my Code for Short-Time-Releases, because it takes away to much energy/time and just for 6month? I will rewrite my code (if needed) when Java 11 (LTS) hits the scene!^^ Maybe Java11 has also backward compatibility, unlike Java 10. If not I will rewrite it then of course!

I recommend using Java 8 until a new LTS has arrived, the big part of all users use still Java 8!
![Java-Version Poll](https://jaxenter.com/wp-content/uploads/2018/04/Screen-Shot-2018-03-22-at-10.53.34-AM.png)

Source: https://jaxenter.com/java-10-interview-series-part-3-142957.html

**Comment by Petschko** [comment]
Since you also had the Oracle ClassNotFoundException, please test the ZIP-File in this issue: https://github.com/Petschko/Java-RPG-Maker-MV-Decrypter/issues/20
