### ISSUE TITLE
How to decrypt encrypted JSON and confused JS files?

### ISSUE THREAD

**Issue by 282167361** [Petschko/Java-RPG-Maker-MV-Decrypter#40]

**Comment by Petschko** [comment]
Hey please provide a detailed description of your problem

**Comment by 282167361** [comment]
> Hey please provide a detailed description of your problem

JSON content is encrypted, JS content is obfuscated, and the game cannot run, what should I do?

**Comment by Petschko** [comment]
When the game doesnt start, it seems its more a problem from the Game dev

**Comment by 282167361** [comment]
> When the game doesnt start, it seems its more a problem from the Game dev

Mainly because JSON files and JS files are encrypted

**Comment by Petschko** [comment]
Anyway with that little information provided, I cant help, feel free to open a new ticket with a more detailed description, which include all details such as:
- Game Name
- Detailed description of the Problem
- Description what you have tried so far
- Maybe example Files
- Additional logs if you have some
- Screenshots

I close this now because I can only guess on your current problem without more informations
